apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations: 
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  loadBalancerSourceRanges:
    - 10.142.0.0/20
    - 10.78.0.0/20
    - 10.12.0.0/20
  ports:
    - name: pgbouncer
      port: 5432
      protocol: TCP
      targetPort: pgbouncer
  selector:
    app: {{ .Release.Name }}
